eWomanPM.MVC/Controllers/ProjectController.cs
using eWomanPM.MVC.Models;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace eWomanPM.MVC.Controllers
{
    public class ProjectController : Controller
    {
        // GET: Project

        [HttpPost]
        public ActionResult Index(string name, string clientName, int type)
        {
            FillDropdown();
            HttpResponseMessage reponse = GlobalVariables.webApiClient.GetAsync("api/Project").Result;
            var resut = reponse.Content.ReadAsAsync<IEnumerable<ProjectModel>>().Result;
            var list = resut.AsQueryable();
            if (!string.IsNullOrEmpty(name))
            {
                list = list.Where(p => p.Name.Contains(name));
            }
            if (!string.IsNullOrEmpty(clientName))
            {
                list = list.Where(p => p.ClientName.Contains(clientName));
            }
            if (type > 0)
            {
                list = list.Where(p => p.ProjectTypeId == type);
            }
            return View(list);
        }
        public ActionResult Index()
        {
            FillDropdown();
            HttpResponseMessage reponse = GlobalVariables.webApiClient.GetAsync("api/Project").Result;
            var resut = reponse.Content.ReadAsAsync<IEnumerable<ProjectModel>>().Result;
            return View(resut);
        }

        // GET: Project/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Project/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Project/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Project/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Project/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Project/Delete/5
        public ActionResult Delete(int id)
        {
            HttpResponseMessage response = GlobalVariables.webApiClient.DeleteAsync("api/Project/" + id.ToString()).Result;
            TempData["SucessMessage"] = "Deleted succesfully";
            return RedirectToAction("Index");
        }
        private void FillDropdown()
        {
            List<SelectListItem> projectTypes = new List<SelectListItem>
                {
                  new SelectListItem {  Text = "Select One", Value = "0"},
                  new SelectListItem {  Text = "Fixed Price ", Value = "1"},
                     new SelectListItem { Text = "Time & Material", Value = "2"},

                     };
            List<SelectListItem> tecnologies = new List<SelectListItem>
                {
                  new SelectListItem {  Text = "Select One ", Value = "0"},
                  new SelectListItem {  Text = "C# ", Value = "1"},
                     new SelectListItem { Text = "PHP", Value = "2"},
                       new SelectListItem { Text = "Java", Value = "3"},
                     };
            ViewBag.ProjectTypes = projectTypes;
            ViewBag.Tecnologies = tecnologies;
        }
        public ActionResult AddOrEdit(int id = 0, bool disabled = false)
        {
            FillDropdown();
            ViewBag.disabled = disabled;
            if (id == 0)
            {
                return View(new ProjectModel());
            }
            else
            {

                HttpResponseMessage reponse = GlobalVariables.webApiClient.GetAsync("api/Project/" + id.ToString()).Result;

                HttpResponseMessage reponseDocument = GlobalVariables.webApiClient.GetAsync("api/Document").Result;
                var resut = reponseDocument.Content.ReadAsAsync<IEnumerable<ProjectModel>>().Result;
                ViewBag.Files = resut;

                HttpResponseMessage reponsetrackerChange = GlobalVariables.webApiClient.GetAsync("api/Change").Result;
                var trackerChangeResult = reponsetrackerChange.Content.ReadAsAsync<IEnumerable<TrackerChangeModel>>().Result;
                ViewBag.Files = resut;
                ViewBag.TrackerChanges = trackerChangeResult;
                return View(reponse.Content.ReadAsAsync<ProjectModel>().Result);
            }
            return View(new ProjectModel());
        }
        [HttpPost]
        public ActionResult AddOrEdit(ProjectModel projectModel)
        {
            FillDropdown();
            if (projectModel.Id == 0)
            {
                HttpResponseMessage response = GlobalVariables.webApiClient.PostAsJsonAsync("api/Project/", projectModel).Result;
                TempData["SucessMessage"] = "Added succesfully";
            }
            else
            {
                HttpResponseMessage response = GlobalVariables.webApiClient.PutAsJsonAsync("api/Project/" + projectModel.Id.ToString(), projectModel).Result;
                TempData["SucessMessage"] = "Modified succesfully";
            }

            return RedirectToAction("Index");
        }
        // POST: Project/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

eWomanPM.MVC/Views/Project/AddOrEdit.cshtml
@model eWomanPM.MVC.Models.ProjectModel

@{
    ViewBag.Title = "AddOrEdit";
}
@*<link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/
    jquery-ui.css" />*@
<div class="form-inline well well-sm">
    @using (Html.BeginForm())
    {
        @Html.HiddenFor(model => model.Id);
        <div class="row">
            <div class="col-md-3">
                @Html.LabelFor(model => model.Name, new { @class = "col-2 col-form-label " })
                @Html.TextBoxFor(model => model.Name, ViewBag.disabled == false ? new { @class = "form-control" } : (object)new { @class = "form-control", disabled = "disabled" })
                @Html.ValidationMessageFor(model => model.Name, string.Empty, new { @class = "text-danger" })
            </div>
            <div class="col-md-3">
                @Html.LabelFor(model => model.ClientName, new { @class = "col-2 col-form-label" })
                @Html.TextBoxFor(model => model.ClientName, ViewBag.disabled == false ? new { @class = "form-control" } : (object)new { @class = "form-control", disabled = "disabled" })
                @Html.ValidationMessageFor(model => model.ClientName, string.Empty, new { @class = "text-danger" })
            </div>
            <div class="col-md-3">
                @Html.LabelFor(model => model.ProjectTypeId)
                @Html.DropDownListFor(model => model.ProjectTypeId, new SelectList(ViewBag.ProjectTypes, "Value", "Text"), ViewBag.disabled == false ? new { @class = "form-control" } : (object)new { @class = "form-control", disabled = "disabled" })
                @Html.ValidationMessageFor(model => model.ProjectTypeId, string.Empty, new { @class = "text-danger" })
            </div>
            <div class="col-md-3">
                <label for="example-text-input" class="col-2 col-form-label">Technology</label>
                @Html.DropDownListFor(model => model.Technology, new SelectList(ViewBag.Tecnologies, "Value", "Text"), ViewBag.disabled == false ? new { @class = "form-control" } : (object)new { @class = "form-control", disabled = "disabled" })

            </div>
        </div>
        <div class="form-inline row">
            <div class="col-md-3">
                @Html.LabelFor(model => model.Cost, new { @class = "col-2 col-form-label" })
                @Html.TextBoxFor(model => model.Cost, ViewBag.disabled == false ? new { @class = "form-control" } : (object)new { @class = "form-control", disabled = "disabled" })
                @Html.ValidationMessageFor(model => model.Cost, string.Empty, new { @class = "text-danger" })
            </div>
            <div class="col-md-3">
                <label for="example-text-input" class="col-2 col-form-label">Date</label>
                @Html.TextBoxFor(model => model.Date, ViewBag.disabled == false ? new { @class = "form-control" } : (object)new { @class = "form-control", disabled = "disabled" })
                @Html.ValidationMessageFor(model => model.Date, string.Empty, new { @class = "text-danger" })

            </div>
            <div class="col-md-3">
                <label for="example-text-input" class="col-2 col-form-label">Start Date</label>
                @Html.TextBoxFor(model => model.StartDate, ViewBag.disabled == false ? new { @class = "form-control" } : (object)new { @class = "form-control", disabled = "disabled" })
                @Html.ValidationMessageFor(model => model.StartDate)
            </div>
            <div class="col-md-3">
                <label for="example-text-input" class="col-2 col-form-label">End Date</label>
                @Html.TextBoxFor(model => model.EndDate, ViewBag.disabled == false ? new { @class = "form-control" } : (object)new { @class = "form-control", disabled = "disabled" })
                @Html.ValidationMessageFor(model => model.EndDate)
            </div>

        </div>
        <div class="form-inline row">

            <div class="col-md-12 " tabindex="11" style="margin-top: 5px">
                @Html.LabelFor(model => model.Description)
                @Html.TextAreaFor(model => model.Description, 3, 100, ViewBag.disabled == false ? new { @class = "form-control" } : (object)new { @class = "form-control", disabled = "disabled" })
                @Html.ValidationMessageFor(model => model.Description, string.Empty, new { @class = "text-danger" })


            </div>

        </div>
        <div class="form-group" style="text-align: right;margin-top:5px">
            <input type="submit" class="btn btn-success" value="Save" />

            <a href="@Url.Action("AddOrEdit","Project")" class="btn btn-info">Create New</a>
            <a href="@Url.Action("Index","Project")" class="btn btn-info">Back</a>
        </div>
    }

</div>
<div class="tabbable  ">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#pane1" data-toggle="tab">Documents</a></li>
        <li><a href="#pane2" data-toggle="tab">History</a></li>
        <li><a href="#pane3" data-toggle="tab">Comments</a></li>
    </ul>
    <div class="tab-content">
        <div id="pane1" class="tab-pane active">
            <div class="form-inline" style="margin-top: 8px">
                <fieldset>
                    <legend>Chose file</legend>

                    @using (Html.BeginForm("Upload", "Upload", new { projectId = @Model.Id }, FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {

                        <div class="fileinput fileinput-new" data-provides="fileinput">
                            <span class="btn btn-default btn-file"><span> </span><input type="file" name="file" /></span>
                            <input type="submit" name="Submit" id="Submit" value="Upload" />
                        </div>

                    }
                </fieldset>

            </div>
            <table class="table table-responsive well">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Date</th>
                        <th></th>
                    </tr>
                </thead>
                @if (ViewBag.Files != null)
                {
                    foreach (var item in ViewBag.Files)
                    {
                        <tr>
                            <td>@item.Name</td>
                            <td>@item.Date</td>
                            <td>@Html.ActionLink("Donwload", "DownloadFile", "Upload", new { documentId = item.Id }, null)</td>
                        </tr>
                    }
                }


            </table>

        </div>
        <div id="pane2" class="tab-pane">
            <table class="table table-responsive well">
                <thead>
                    <tr>
                        <th>Property Name</th>
                        <th>Old Value</th>
                        <th>New Value</th>
                        <th>Date</th>
                        <th></th>
                    </tr>
                </thead>
                @if (ViewBag.TrackerChanges != null)
                {
                    foreach (var item in ViewBag.TrackerChanges)
                    {
                        <tr>
                            <td>@item.PropertyName</td>
                            <td>@item.OldValue</td>
                            <td>@item.NewValue</td>
                            <td>@item.DateChanged</td>
                        </tr>
                    }
                }


            </table>

        </div>
        <div id="pane3" class="tab-pane">
            <div class="row">
                <div class="col-md-12 " tabindex="11" style="margin-top: 5px">
                    <textarea placeholder="Comment" class="form-control"
                              rows="2" cols="1" style="width: 100%"></textarea>

                </div>
            </div>
        </div>
    </div>
</div>

<script src="//code.jquery.com/jquery-1.10.2.js" type="text/javascript"></script>
<script src="//code.jquery.com/ui/1.11.2/jquery-ui.js" type="text/javascript"></script>
<script type="text/javascript">
    $("#Date").datepicker({
        changeMonth: true,
        changeYear: true
    });
    $("#StartDate").datepicker({
        changeMonth: true,
        changeYear: true
    });
    $("#EndDate").datepicker({
        changeMonth: true,
        changeYear: true
    });

</script>
@Scripts.Render("~/bundles/jqueryval")

eWomanPM.MVC/Views/Project/Index.cshtml
@model IEnumerable<eWomanPM.MVC.Models.ProjectModel>

@{
    ViewBag.Title = "Index";
}
<link href="~/Content/alertifyjs/alertify.min.css" rel="stylesheet" />
<div class="form-inline well-sm">
    @using (Html.BeginForm("Index", "Project", FormMethod.Post, new { @class = "Search-form" }))
    {
        <fieldset>
            <legend>Filter</legend>
            <div class="row">
                <div class="col-md-3">
                    <label>Name</label>
                </div>
                <div class="col-md-3">
                    <label>Cliente Name</label>
                </div>
                <div class="col-md-3">
                    <label>Type</label>
                </div>

            </div>
            <div class="row">
                <div class="col-md-3">
                    @Html.TextBox("name", null, new { @class = "form-control" })

                </div>
                <div class="col-md-3">
                    @Html.TextBox("clientName", null, new { @class = "form-control" })
                </div>
                <div class="col-md-3">
                    @Html.DropDownList("type", new SelectList(ViewBag.ProjectTypes, "Value", "Text"), new { @class = "form-control" })
                </div>
                @*<div class="col-md-3">
                        @Html.TextBox("date", null, new { @class = "form-control" })
                    </div>*@
                <div class="col-md-3">
                    <input type="submit" value="Apply Filter" class="btn btn-success" />
                </div>
            </div>
        </fieldset>
    }


</div>

<p>
    @*<a href="@Url.Action("AddOrEdit","Project")" class="btn btn-success">Apply Filter</a>*@

    <a href="@Url.Action("AddOrEdit","Project")" class="btn btn-info">Create New</a>
</p>


<table class="table table-striped">

    <thead class="table-heading">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)


            </th>
            <th>
                Client Name
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                Status
            </th>
            <th>
              Start Date
            </th>
            <th>
                End Date
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cost)
            </th>
            <th></th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>

                @Html.DisplayFor(modelItem => item.ClientName)
            </td>


            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status.Name, item.StatusId == 4 ? new { @class = "text-primary" } :  new { @class = "text-info" })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cost)
            </td>
            <td>
                @if (item.StatusId != 4)
                {
                    <a href="@Url.Action("AddOrEdit", "Project", new { Id = item.Id, })" class="btn btn-default">Detail</a>
                    <a href="@Url.Action("AddOrEdit", "Project", new { Id = item.Id })" class="btn btn-primary">Edit</a>

                    <a onclick="Delete(@item.Id)" class="btn btn-danger">Delete</a>
                }


            </td>
        </tr>
    }

</table>

<script src="~/Scripts/jquery-3.2.1.min.js"></script>
<script src="~/Scripts/alertify.min.js"></script>
<script>

    $(function () {

        var sucessMessage = '@TempData["SucessMessage"]'
        if (sucessMessage != '') {
            alertify.success(sucessMessage)
        }

    });
    function Delete(id) {
 
        alertify.confirm("eWomanPM", "Are you sure to delete this project?", function () {
            window.location.href = '@Url.Action("Delete", "Project")/' + id;
        }, null);
    }
</script>